# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])

languages([
  'en-US'
])

# Where should the resulting screenshots be stored?
screenshots_path "./screenshots"

clear_previous_screenshots # remove the '#'' to clear all previously generated screenshots before creating new ones

# JavaScript UIAutomation file
# js_file './snapshot.js'

# The name of the project's scheme

scheme "Signal-Snapshots"

# By default, the latest version should be used automatically. If you want to change it, do it here
#ios_version '8.1'

# Custom Callbacks

setup_for_device_change do |device, udid|
  puts "Preparing device: #{device} with udid #{udid}"
  # Completely reset the device before we start taking screenshots
  system("xcrun simctl erase #{udid}")
 
  puts "Copying AddressBook and KeyChain items"
  FileUtils.cp_r 'SampleData/AddressBook', "#{Dir.home}/Library/Developer/CoreSimulator/Devices/#{udid}/data/Library/"
  FileUtils.cp_r 'SampleData/Keychains', "#{Dir.home}/Library/Developer/CoreSimulator/Devices/#{udid}/data/Library/"
  
  puts "Copying populated database"
  
  folder_name = "SampleDocuments"
  app_path = "/tmp/snapshot/build/Signal.app/"

  FileUtils.mkdir_p(File.join(app_path, folder_name))

  Dir.glob(File.join('SampleData/Documents', '*')).each do |example_path|
    FileUtils.cp_r(example_path, File.join(app_path, folder_name)) rescue nil # in case the file already exists
  end

end

# setup_for_language_change do |lang, device|
#   puts "Running #{lang} on #{device}"
#   system("./popuplateDatabase.sh")
# end

# teardown_language do |lang, device|
#   puts "Finished with #{lang} on #{device}"
# end

teardown_device do |device, udid|
  puts "Cleaning device #{device}"
  system("xcrun simctl erase #{udid}")
end
